language: java
jdk:
- oraclejdk8

install: true

# to get the effective pom, add help:effective-pom
script: mvn clean install site

cache:
  directories:
  - $HOME/.m2
  
notifications:
  email:
    - erik.koerber@gmail.com
